server:
  port: 7002
eureka:
  instance:
    hostname: springCloudEureka7002.com   #eureka服务端的实例名称，配置了集群，修改了本机的hosts文件
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false       #false表示自己端就是注册中心，我的职责是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://springCloudEureka7001.com:7001/eureka/,http://springCloudEureka7003.com:7003/eureka/

      #修改      域名映射     C:\Windows\System32\drivers\etc  hosts
      # 127.0.0.1       springCloudEureka7001.com
      # 127.0.0.1       springCloudEureka7002.com
      # 127.0.0.1       springCloudEureka7003.com
