server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:yangliuwilow/springcloud-config.git #GitHub上面的git仓库名字
 

